<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260217111217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE categoria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE categoria_plato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_categoria_id INT DEFAULT NULL, id_plato_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_907CF78610560508 ON categoria_plato (id_categoria_id)');
        $this->addSql('CREATE INDEX IDX_907CF786E000E57A ON categoria_plato (id_plato_id)');
        $this->addSql('CREATE TABLE favorito (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_plato_id INT DEFAULT NULL, id_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_881067C7E000E57A ON favorito (id_plato_id)');
        $this->addSql('CREATE INDEX IDX_881067C779F37AE5 ON favorito (id_user_id)');
        $this->addSql('CREATE TABLE ingrediente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ingrediente_plato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, id_ingrediente_id INT DEFAULT NULL, id_plato_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FB1AE8844BF8F88B ON ingrediente_plato (id_ingrediente_id)');
        $this->addSql('CREATE INDEX IDX_FB1AE884E000E57A ON ingrediente_plato (id_plato_id)');
        $this->addSql('CREATE TABLE pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, direccion_envio VARCHAR(255) NOT NULL, metodo_pago VARCHAR(255) NOT NULL, id_user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C4EC16CE79F37AE5 ON pedido (id_user_id)');
        $this->addSql('CREATE TABLE plato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nombre VARCHAR(255) NOT NULL, url_img VARCHAR(255) NOT NULL, origen VARCHAR(255) NOT NULL, precio VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE plato_pedido (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, cantidad_plato INT NOT NULL, id_plato_id INT DEFAULT NULL, id_pedido_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3F4322D7E000E57A ON plato_pedido (id_plato_id)');
        $this->addSql('CREATE INDEX IDX_3F4322D7C861D91D ON plato_pedido (id_pedido_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, nombre VARCHAR(255) NOT NULL, telefono INT NOT NULL, direccion VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE categoria_plato ADD CONSTRAINT FK_907CF78610560508 FOREIGN KEY (id_categoria_id) REFERENCES categoria (id)');
        $this->addSql('ALTER TABLE categoria_plato ADD CONSTRAINT FK_907CF786E000E57A FOREIGN KEY (id_plato_id) REFERENCES plato (id)');
        $this->addSql('ALTER TABLE favorito ADD CONSTRAINT FK_881067C7E000E57A FOREIGN KEY (id_plato_id) REFERENCES plato (id)');
        $this->addSql('ALTER TABLE favorito ADD CONSTRAINT FK_881067C779F37AE5 FOREIGN KEY (id_user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE ingrediente_plato ADD CONSTRAINT FK_FB1AE8844BF8F88B FOREIGN KEY (id_ingrediente_id) REFERENCES ingrediente (id)');
        $this->addSql('ALTER TABLE ingrediente_plato ADD CONSTRAINT FK_FB1AE884E000E57A FOREIGN KEY (id_plato_id) REFERENCES plato (id)');
        $this->addSql('ALTER TABLE pedido ADD CONSTRAINT FK_C4EC16CE79F37AE5 FOREIGN KEY (id_user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE plato_pedido ADD CONSTRAINT FK_3F4322D7E000E57A FOREIGN KEY (id_plato_id) REFERENCES plato (id)');
        $this->addSql('ALTER TABLE plato_pedido ADD CONSTRAINT FK_3F4322D7C861D91D FOREIGN KEY (id_pedido_id) REFERENCES pedido (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE categoria_plato DROP CONSTRAINT FK_907CF78610560508');
        $this->addSql('ALTER TABLE categoria_plato DROP CONSTRAINT FK_907CF786E000E57A');
        $this->addSql('ALTER TABLE favorito DROP CONSTRAINT FK_881067C7E000E57A');
        $this->addSql('ALTER TABLE favorito DROP CONSTRAINT FK_881067C779F37AE5');
        $this->addSql('ALTER TABLE ingrediente_plato DROP CONSTRAINT FK_FB1AE8844BF8F88B');
        $this->addSql('ALTER TABLE ingrediente_plato DROP CONSTRAINT FK_FB1AE884E000E57A');
        $this->addSql('ALTER TABLE pedido DROP CONSTRAINT FK_C4EC16CE79F37AE5');
        $this->addSql('ALTER TABLE plato_pedido DROP CONSTRAINT FK_3F4322D7E000E57A');
        $this->addSql('ALTER TABLE plato_pedido DROP CONSTRAINT FK_3F4322D7C861D91D');
        $this->addSql('DROP TABLE categoria');
        $this->addSql('DROP TABLE categoria_plato');
        $this->addSql('DROP TABLE favorito');
        $this->addSql('DROP TABLE ingrediente');
        $this->addSql('DROP TABLE ingrediente_plato');
        $this->addSql('DROP TABLE pedido');
        $this->addSql('DROP TABLE plato');
        $this->addSql('DROP TABLE plato_pedido');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
